### ISSUE TITLE
API Doesn't work via Postman

### ISSUE THREAD

**Issue by jitenderbadoni** [tapkey/tapkey-api-samples-java#3]
I am facing an issue in creating a new user of Identity provider user ID. I am sharing complete information.

URL: `https://my.tapkey.com/api/v1/Owners/{{OAuthClientId}}/IdentityProviders/{{ipId}}/Users  `
Method: `PUT`
Headers: `Authorization: Bearer + token`
Body: `{   "ipUserId": 24 }`

Where the ipUserId is my external user of my database.

I am getting 403 Forbidden code in response and nothing else.

Let me know if you need anything else to resolve this issue.

**Comment by sebastianhaas** [comment]
Please contact us via support@tapkey.com if you need assistance with the Tapkey Management API. Github Issues are for bug reports and feature requests only.
